steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pdf-parser:latest', '.']

- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/pdf-parser:latest']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'ocr-api'
  - '--image=gcr.io/$PROJECT_ID/pdf-parser:latest'
  - '--platform=managed'
  - '--region=us-central1'
  - '--allow-unauthenticated'
  - '--port=8080'

# Store logs only in Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/$PROJECT_ID/pdf-parser:$COMMIT_SHA"
