steps:
# 1️⃣ Build the Docker image with a valid tag
- name: "gcr.io/cloud-builders/docker"
  args:
    - "build"
    - "-t"
    - "gcr.io/practical-theme-425612-n0/pdf-parser:latest"
    - "-t"
    - "gcr.io/practical-theme-425612-n0/pdf-parser$_SHORT_SHA"
    - "."
  env:
    - "SHORT_SHA=$_SHORT_SHA"

# 2️⃣ Push the Docker images to Google Container Registry
- name: "gcr.io/cloud-builders/docker"
  args:
    - "push"
    - "gcr.io/practical-theme-425612-n0/pdf-parser:latest"

- name: "gcr.io/cloud-builders/docker"
  args:
    - "push"
    - "gcr.io/practical-theme-425612-n0/pdf-parser$_SHORT_SHA"

# 3️⃣ Deploy the latest image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - "run"
    - "deploy"
    - "ocr-api"
    - "--image=gcr.io/practical-theme-425612-n0/pdf-parser:latest"
    - "--region=us-central1"
    - "--platform=managed"
    - "--allow-unauthenticated"
    - "--port=8080"

# 4️⃣ Allow public access to Cloud Run service
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - "run"
    - "services"
    - "add-iam-policy-binding"
    - "ocr-api"
    - "--region=us-central1"
    - "--member=allUsers"
    - "--role=roles/run.invoker"

substitutions:
  _SHORT_SHA: "latest"

images:
  - "gcr.io/practical-theme-425612-n0/pdf-parser:latest"
  - "gcr.io/practical-theme-425612-n0/pdf-parser$_SHORT_SHA"

timeout: "1200s"  # Allow 20 minutes for builds
