steps:
# 1️⃣ Build the Docker image with a valid tag
- name: "gcr.io/cloud-builders/docker"
  args:
    - "build"
    - "-t"
    - "gcr.io/practical-theme-425612-n0/pdf-parser:latest"
    - "-t"
    - "gcr.io/practical-theme-425612-n0/pdf-parser:$SHORT_SHA"
    - "."

# 2️⃣ Push both `latest` and commit-tagged image
- name: "gcr.io/cloud-builders/docker"
  args:
    - "push"
    - "gcr.io/practical-theme-425612-n0/pdf-parser:latest"

- name: "gcr.io/cloud-builders/docker"
  args:
    - "push"
    - "gcr.io/practical-theme-425612-n0/pdf-parser:$SHORT_SHA"

# 3️⃣ Deploy to Cloud Run using latest image
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - "run"
    - "deploy"
    - "ocr-api"
    - "--image=gcr.io/practical-theme-425612-n0/pdf-parser:latest"
    - "--region=us-central1"
    - "--platform=managed"
    - "--allow-unauthenticated"
    - "--port=8080"

# 4️⃣ (Optional) Grant public access if needed
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - "run"
    - "services"
    - "add-iam-policy-binding"
    - "ocr-api"
    - "--region=us-central1"
    - "--member=allUsers"
    - "--role=roles/run.invoker"

substitutions:
  SHORT_SHA: "${SHORT_SHA}"

images:
  - "gcr.io/practical-theme-425612-n0/pdf-parser:latest"
  - "gcr.io/practical-theme-425612-n0/pdf-parser:$SHORT_SHA"

timeout: "1200s" # Allow 20 minutes for the build to prevent timeouts
