steps:
# 1️⃣ Build the Docker image with a unique tag
- name: "gcr.io/cloud-builders/docker"
  args:
    - "build"
    - "-t"
    - "gcr.io/practical-theme-425612-n0/pdf-parser:$COMMIT_SHA"
    - "."

# 2️⃣ Push the image to Google Container Registry
- name: "gcr.io/cloud-builders/docker"
  args:
    - "push"
    - "gcr.io/practical-theme-425612-n0/pdf-parser:$COMMIT_SHA"

# 3️⃣ Deploy the container to Google Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - "run"
    - "deploy"
    - "ocr-api"
    - "--image=gcr.io/practical-theme-425612-n0/pdf-parser:$COMMIT_SHA"
    - "--region=us-central1"
    - "--platform=managed"
    - "--allow-unauthenticated"
    - "--port=8080"

# 4️⃣ Set IAM policies to allow unauthenticated access (optional)
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - "run"
    - "services"
    - "add-iam-policy-binding"
    - "ocr-api"
    - "--region=us-central1"
    - "--member=allUsers"
    - "--role=roles/run.invoker"

substitutions:
  _DEFAULT_LOGS_BUCKET_BEHAVIOR: "CLOUD_LOGGING_ONLY"
  COMMIT_SHA: "${SHORT_SHA}"

images:
  - "gcr.io/practical-theme-425612-n0/pdf-parser:$COMMIT_SHA"

timeout: "1200s" # 20 minutes timeout to prevent build failures on slow connections
